'use client';

import Link from 'next/link';
import { ChangeEvent, useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, Check, Clock3, Download, FileText, History, Send, Upload } from 'lucide-react';
import mammoth from 'mammoth/mammoth.browser';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import { RichEditor, type EditorDocument } from '@/components/rich-editor';
import { apiFetch } from '@/lib/api';
import type { ChapterDetail, ChapterRevision } from '@/lib/types';

export default function ChapterEditorPage({params}:{params:{storyId:string;chapterId:string}}){
 const[chapter,setChapter]=useState<ChapterDetail|null>(null);const[title,setTitle]=useState('');const[content,setContent]=useState<EditorDocument>({type:'doc'});const[plainText,setPlainText]=useState('');const[saveState,setSaveState]=useState<'saved'|'saving'|'dirty'|'error'>('saved');const[revisions,setRevisions]=useState<ChapterRevision[]>([]);const[showHistory,setShowHistory]=useState(false);const version=useRef(1);const hydrated=useRef(false);const importRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{const data=await apiFetch<ChapterDetail>(`/v1/me/stories/${params.storyId}/chapters/${params.chapterId}`);setChapter(data);setTitle(data.title);setContent(normalizeDocument(data.content));setPlainText(data.plainText??'');version.current=data.contentVersion??1;setSaveState('saved');setTimeout(()=>{hydrated.current=true},0);},[params.chapterId,params.storyId]);useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!hydrated.current||!chapter)return;setSaveState('dirty');const timer=setTimeout(async()=>{setSaveState('saving');try{const saved=await apiFetch<ChapterDetail>(`/v1/me/stories/${params.storyId}/chapters/${params.chapterId}`,{method:'PATCH',body:JSON.stringify({title,content,plainText,expectedVersion:version.current})});version.current=saved.contentVersion??version.current+1;setSaveState('saved');}catch{setSaveState('error');}},900);return()=>clearTimeout(timer);},[chapter,content,params.chapterId,params.storyId,plainText,title]);
 async function publish(){await apiFetch(`/v1/me/stories/${params.storyId}/chapters/${params.chapterId}/publish`,{method:'POST'});await load();}
 async function history(){setRevisions(await apiFetch<ChapterRevision[]>(`/v1/me/stories/${params.storyId}/chapters/${params.chapterId}/revisions`));setShowHistory(true)}
 async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(file.name.endsWith('.docx')){const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});setPlainText(result.value);setContent(textToDoc(result.value));}else{const text=await file.text();setPlainText(text);setContent(textToDoc(text));}event.target.value='';}
 async function exportDocx(){const doc=new Document({sections:[{children:[new Paragraph({children:[new TextRun({text:title,bold:true,size:36})]}),...plainText.split(/\n\s*\n/).map((text)=>new Paragraph(text))]}]});download(await Packer.toBlob(doc),`${title||'capitulo'}.docx`)}
 function exportMarkdown(){download(new Blob([`# ${title}\n\n${plainText}`],{type:'text/markdown'}),`${title||'capitulo'}.md`)}
 if(!chapter)return <div className="editor-page"><div className="empty-state">Cargando editor...</div></div>;
 return <div className="editor-page"><header className="editor-header"><Link href={`/studio/${params.storyId}`}><ArrowLeft size={19}/><span>Capitulos</span></Link><div className={`save-indicator ${saveState}`}>{saveState==='saving'?<Clock3 size={15}/>:<Check size={15}/>} {saveState==='saved'?'Guardado':saveState==='saving'?'Guardando...':saveState==='error'?'Error al guardar':'Cambios sin guardar'}</div><div className="editor-actions"><button onClick={()=>importRef.current?.click()}><Upload size={17}/>Importar</button><div className="export-menu"><button><Download size={17}/>Exportar</button><div><button onClick={exportMarkdown}>Markdown</button><button onClick={exportDocx}>DOCX</button></div></div><button onClick={history}><History size={17}/>Versiones</button><button className="publish-command" onClick={publish}><Send size={17}/>{chapter.status==='published'?'Actualizar publicado':'Publicar'}</button><input ref={importRef} hidden type="file" accept=".docx,.md,.markdown,text/markdown" onChange={importFile}/></div></header><main className="writing-desk"><input className="chapter-title-input" value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="Titulo del capitulo"/><div className="writing-meta"><span>Capitulo {chapter.position}</span><span>{plainText.trim()?plainText.trim().split(/\s+/).length:0} palabras</span><span>{Math.max(1,Math.ceil((plainText.trim()?plainText.trim().split(/\s+/).length:0)/200))} min de lectura</span></div><RichEditor key={`${chapter.id}-${chapter.contentVersion}`} initialContent={content} onChange={(json,text)=>{setContent(json);setPlainText(text)}}/></main>{showHistory&&<aside className="history-panel"><div><h2>Historial de versiones</h2><button onClick={()=>setShowHistory(false)}>Cerrar</button></div>{revisions.map((item)=><article key={item.id}><FileText size={18}/><div><strong>Version {item.version}</strong><span>{new Date(item.createdAt).toLocaleString('es-CL')} · {item.reason}</span></div><button onClick={async()=>{await apiFetch(`/v1/me/stories/${params.storyId}/chapters/${params.chapterId}/revisions/${item.id}/restore`,{method:'POST'});setShowHistory(false);hydrated.current=false;await load();}}>Restaurar</button></article>)}</aside>}</div>;
}
function normalizeDocument(value:unknown):EditorDocument{if(value&&typeof value==='object'&&'type'in value)return value as EditorDocument;return textToDoc(Array.isArray(value)?value.join('\n\n'):String(value??''))}function textToDoc(text:string):EditorDocument{return{type:'doc',content:text.split(/\n\s*\n/).filter(Boolean).map((paragraph)=>({type:'paragraph',content:[{type:'text',text:paragraph.trim()}]}))}}function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
